# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py
git:
  depth: 20

language: python
python:
  - 3.6
  - 3.7-dev

matrix:
  allow_failures:
    - python: 3.7-dev

install:
  - pip install --upgrade setuptools pip pytest-cov python-coveralls
  - pip install .[test]
  - python setup.py build bdist_wheel

script:
  - pytest --pyargs -v tests --cov=polyvers --cov-report term-missing
  - flake8 --show-source

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then coveralls; fi
